// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smdfbkezphprxegjqbsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZGZia2V6cGhwcnhlZ2pxYnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjAwMjQsImV4cCI6MjA3NjYzNjAyNH0.R4OaENcdlK5xF6nb0la9xAZBgARZOjq4a3XSyhLplN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});